/**
 * Auto-generated by scripts/sync-guest-review-gallery.mjs — do not edit by hand.
 * Run: npm run sync:guest-review-gallery
 * Source: public/images/ (flat; juniorsuitedeluxesingle*.webp)
 */
export const GUEST_REVIEW_GALLERY_IMAGES = [
  'images/juniorsuitedeluxesingle11468-jpg-68bb304766388dd33271dda0399.webp',
  'images/juniorsuitedeluxesingle13985-jpg-11ce962885ac99463020599860f.webp',
  'images/juniorsuitedeluxesingle14812-jpg-36e3f833ed9133889b21a09eaa1.webp',
  'images/juniorsuitedeluxesingle1593-jpg-b2a70f1f45abed688344f0350169.webp',
  'images/juniorsuitedeluxesingle2245-jpg-a39081733ae0bf10511bd6b99b9e.webp',
  'images/juniorsuitedeluxesingle4217-jpg-eb30cde21572fb4f089c74f52004.webp',
  'images/juniorsuitedeluxesingle6350-jpg-77bc0374ff65f1413f282f7701bb.webp',
  'images/juniorsuitedeluxesingle7328-jpg-0dcbb1f2505589850763959ad124.webp',
  'images/juniorsuitedeluxesingle9929-jpg-c2e7aa4c256d12f7e09d6cbb2b30.webp',
] as const;
