/**
 * Auto-generated by scripts/sync-hero-gallery.mjs — do not edit by hand.
 * Run: npm run sync:hero-gallery
 */
export const HERO_GALLERY_FILENAMES = [
  'beach00217-jpg-8dcbbbd78a5ce3952522dff211697668.webp',
  'beach5764-jpg-9a9cbc14f7805c5f429e15dcf6bf94e7.webp',
  'breathe1-680px422-jpg-f4bef3ac88d43f92d480eaeaec56833a.webp',
  'buffetbayou7591-jpg-a09c4018c8a74611962a7d5ff0d1d43e.webp',
  'fotosrivieramaya5459-jpg-527be2c744e131a143a17b8333a8c66e.webp',
  'fotosrivieramaya7517-jpg-6164165bed6ea22085458fbb0103c3f9.webp',
  'grand-sirenis-riviera-maya-resort-slide1125-jpg-1e13f6b58e1a.webp',
  'gsrm-beyond-flavors-actividades-lifestyle35666-jpg-50210c8e1.webp',
  'gsrm-beyond-flavors-black-sheep5406-jpg-0c55b7009396fb67e169.webp',
  'gsrm-beyond-flavors-bliss61800px216-jpg-40013b94a4d72490ab79.webp',
  'gsrm-beyond-flavors-butchers14305-jpg-859cd8b76bdc9a5952ef53.webp',
  'gsrm-beyond-flavors-tostado-coffe-shop31800px511-jpg-1aa13d7.webp',
  'juniorsuitedeluxesingle1593-jpg-b2a70f1f45abed688344f0350169.webp',
  'juniorsuitedeluxesingle2245-jpg-a39081733ae0bf10511bd6b99b9e.webp',
  'juniorsuitedeluxesingle4217-jpg-eb30cde21572fb4f089c74f52004.webp',
  'juniorsuitedeluxesingle6350-jpg-77bc0374ff65f1413f282f7701bb.webp',
] as const;
