/**
 * Auto-generated by scripts/sync-hero-gallery.mjs - do not edit by hand.
 * Run: npm run sync:hero-gallery
 * Source: public/images/sliding-gallery-hero/ (random 18, seeded for stable builds)
 */
export const HERO_GALLERY_FILENAMES = [
  'images/sliding-gallery-hero/PVRPA_Guest_Room_Superior_Ocean_Front_Room_King_01___K1SF.png',
  'images/sliding-gallery-hero/CUNMC_Lifestyle_Plunge_Pool_Suite_01.png',
  'images/sliding-gallery-hero/Pool___Casa_1___Enclave____Hilton__2.png',
  'images/sliding-gallery-hero/HHR_PUERTOVALLARTA_SPA_SH0172.png',
  'images/sliding-gallery-hero/hilton_Muir_day1-1047-Edit.png',
  'images/sliding-gallery-hero/PVRPA_Convention_Center___Entrance_01.png',
  'images/sliding-gallery-hero/Hilton_Tulum_07271048__2__356270b4e_35629a402.png',
  'images/sliding-gallery-hero/hilton_muir_day2-177-Edit.png',
  'images/sliding-gallery-hero/CUNMC_Lifestyle_Beach_05.png',
  'images/sliding-gallery-hero/Aerial_Hilton_Tulum_072679_2.png',
  'images/sliding-gallery-hero/CUNMC_Lifestyle_Maxal_01.png',
  'images/sliding-gallery-hero/HHR_PUERTOVALLARTA_COCOMAR_SH0286.png',
  'images/sliding-gallery-hero/HHR_PUERTOVALLARTA_POOL_SH2027.png',
  'images/sliding-gallery-hero/HHR_PUERTOVALLARTA_LALUCE_SH0400.png',
  'images/sliding-gallery-hero/CUNMC_Lifestyle_Maxal_Dish_02.png',
  'images/sliding-gallery-hero/CUNMC_Lifestyle_La_Luce_01.png',
  'images/sliding-gallery-hero/HLTON_STTK_007.png',
] as const;
