#!/usr/bin/env python3
"""
Convert a .docx (Word) file to Markdown for docs/reference.
Uses only the Python standard library. Run from repo root:

  Full document:
    python3 scripts/docx_to_md.py docs/grand-sirenis-ulc-lp-copy.docx docs/grand-sirenis-ulc-lp-copy.md

  Interior in-app routes only (accommodations, amenities, things-to-do, all-inclusive + shared footer):
    python3 scripts/docx_to_md.py --interior-only docs/grand-sirenis-ulc-lp-copy.docx docs/grand-sirenis-ulc-lp-copy-interior-pages.md
"""
from __future__ import annotations

import re
import sys
import zipfile
import xml.etree.ElementTree as ET


W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


def _local(tag: str) -> str:
    return f"{{{W}}}{tag}"


def _unescape(s: str) -> str:
    return (
        s.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", '"')
        .replace("&apos;", "'")
    )


def _para_text(p: ET.Element) -> str:
    parts: list[str] = []
    for t in p.iter(_local("t")):
        if t.text:
            parts.append(t.text)
        if t.tail:
            parts.append(t.tail)
    return _unescape("".join(parts)).strip()


def _is_list_item(p: ET.Element) -> bool:
    ppr = p.find(_local("pPr"))
    if ppr is None:
        return False
    if ppr.find(_local("numPr")) is not None:
        return True
    ps = ppr.find(_local("pStyle"))
    if ps is not None and ps.get(_local("val")) == "ListParagraph":
        return True
    return False


def _runs(p: ET.Element) -> list[ET.Element]:
    return list(p.findall(f".//{_local('r')}"))


def _run_bold(r: ET.Element) -> bool:
    rpr = r.find(_local("rPr"))
    if rpr is None:
        return False
    return rpr.find(_local("b")) is not None or rpr.find(_local("bCs")) is not None


def _max_run_sz(p: ET.Element) -> int:
    best = 0
    for r in _runs(p):
        rpr = r.find(_local("rPr"))
        if rpr is None:
            continue
        sz = rpr.find(_local("sz"))
        if sz is not None:
            v = sz.get(_local("val"))
            if v and v.isdigit():
                best = max(best, int(v))
    return best


def _is_horizontal_rule(p: ET.Element, text: str) -> bool:
    if text:
        return False
    ppr = p.find(_local("pPr"))
    if ppr is None:
        return False
    bdr = ppr.find(_local("pBdr"))
    return bdr is not None and bdr.find(_local("bottom")) is not None


def _is_heading_candidate(p: ET.Element, text: str) -> int | None:
    """Return markdown heading level 2–3, or None."""
    if not text or _is_list_item(p):
        return None
    runs = _runs(p)
    if not runs:
        return None
    if not all(_run_bold(r) for r in runs):
        return None
    sz = _max_run_sz(p)
    # Large / section titles in the source doc (half-points).
    if sz >= 40:
        return 2
    if sz >= 26:
        return 3
    # Emoji-prefixed section labels (🏝️ Offer, 📝 Metadata, …)
    if re.match(r"^[\U0001F300-\U0001FAFF\u2600-\u26FF]", text.strip()):
        return 2
    return None


def docx_to_markdown(docx_path: str) -> str:
    with zipfile.ZipFile(docx_path) as z:
        xml_bytes = z.read("word/document.xml")
    root = ET.fromstring(xml_bytes)
    body = root.find(_local("body"))
    if body is None:
        raise SystemExit("Invalid docx: no w:body")

    out: list[str] = []
    front = [
        "---",
        "title: Grand Sirenis ULC LP — copy document",
        "source: docs/grand-sirenis-ulc-lp-copy.docx",
        "note: Generated by scripts/docx_to_md.py — re-run after Word edits.",
        "---",
        "",
    ]
    out.extend(front)

    for p in body.findall(_local("p")):
        text = _para_text(p)
        if _is_horizontal_rule(p, text):
            out.append("\n---\n")
            continue
        if not text:
            out.append("")
            continue
        if _is_list_item(p):
            out.append(f"- {text}")
            continue
        level = _is_heading_candidate(p, text)
        if level:
            out.append(f"{'#' * level} {text}")
            continue
        out.append(text)

    # Collapse excessive blank lines
    md = "\n".join(out)
    md = re.sub(r"\n{4,}", "\n\n\n", md)
    return md.strip() + "\n"


def extract_interior_pages_markdown(full_md: str) -> str:
    """
    Keep copy used by in-app interior routes: the Word section
    'Accommodations Detail — Interior Billing Banner' through content before Thank You pages,
    plus the legal footer block (InteriorFooter).
    """
    lines = full_md.splitlines()

    start = None
    for i, line in enumerate(lines):
        low = line.lower()
        if "accommodations detail" in low and "interior" in low:
            start = i
            break
    if start is None:
        for i, line in enumerate(lines):
            if "accommodations detail" in line.lower():
                start = i
                break
    if start is None:
        raise SystemExit(
            "Interior extract: could not find 'Accommodations Detail — Interior' heading. "
            "Regenerate full markdown first, or update markers in scripts/docx_to_md.py."
        )

    end = len(lines)
    for i in range(start + 1, len(lines)):
        if lines[i].startswith("###") and "Thank You Page" in lines[i]:
            end = i
            break

    core = lines[start:end]
    while core and not core[-1].strip():
        core.pop()
    while core and core[-1].strip() == "---":
        core.pop()
        while core and not core[-1].strip():
            core.pop()

    fstart = None
    for i, line in enumerate(lines):
        if line.startswith("###") and "Footer" in line:
            fstart = i
            break

    footer_lines: list[str] = []
    if fstart is not None:
        for i in range(fstart, len(lines)):
            line = lines[i]
            if i > fstart and line.strip() == "---":
                break
            footer_lines.append(line)

    intro = [
        "---",
        "title: Grand Sirenis ULC LP — interior pages copy only",
        "source: docs/grand-sirenis-ulc-lp-copy.docx",
        "scope: In-app routes `#accommodations`, `#amenities`, `#things-to-do`, `#all-inclusive`",
        "note: Auto-sliced from full export. Master section begins at “Accommodations Detail — Interior Billing Banner”; on-site copy supports Amenities/All-Inclusive; “Things to Do” block supports Things-to-Do page.",
        "---",
        "",
    ]

    body: list[str] = [
        "# Interior pages copy",
        "",
        "Use this file when updating **Accommodations**, **Amenities**, **Things to Do**, and **All-Inclusive** pages. It omits homepage LP, ads, thank-you, and email.",
        "",
        "---",
        "",
    ]
    body.extend(line.rstrip() for line in core)
    if footer_lines:
        body.extend(["", "---", ""])
        body.extend(line.rstrip() for line in footer_lines)

    md = "\n".join(intro + body)
    md = re.sub(r"\n{4,}", "\n\n\n", md)
    return md.strip() + "\n"


def main() -> None:
    argv = list(sys.argv[1:])
    interior_only = False
    if argv and argv[0] == "--interior-only":
        interior_only = True
        argv = argv[1:]

    if len(argv) != 2:
        print(
            "Usage:\n"
            "  python3 scripts/docx_to_md.py <input.docx> <output.md>\n"
            "  python3 scripts/docx_to_md.py --interior-only <input.docx> <output.md>",
            file=sys.stderr,
        )
        sys.exit(1)

    src, dst = argv[0], argv[1]
    md = docx_to_markdown(src)
    if interior_only:
        md = extract_interior_pages_markdown(md)

    with open(dst, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"Wrote {dst}" + (" (interior pages only)" if interior_only else ""))


if __name__ == "__main__":
    main()
